# Generated by Django 5.2.2 on 2025-06-06 20:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef_objetivo', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Coeficientes de la función objetivo.', size=None)),
                ('matriz_restricciones', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), help_text='Matriz de restricciones.', size=None)),
                ('vector_b', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Lado derecho de las restricciones.', size=None)),
                ('desigualdades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), help_text="Lista de desigualdades ('<=', '>=', '=').", size=None)),
                ('tipo_problema', models.CharField(choices=[('max', 'Maximizar'), ('min', 'Minimizar')], default='max', max_length=3)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo Simplex',
                'verbose_name_plural': 'Cálculos Simplex',
                'ordering': ['-creado'],
            },
        ),
    ]
