# Generated by Django 5.2.2 on 2025-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplex',
            name='resultado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
