# Generated by Django 5.2.2 on 2025-06-16 00:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0002_problemasimplex_delete_simplex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problemasimplex',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problemasimplex',
            name='advertencias',
            field=models.JSONField(blank=True, help_text='Advertencias generadas durante el proceso de solución', null=True),
        ),
        migrations.AddField(
            model_name='problemasimplex',
            name='estado',
            field=models.CharField(choices=[('optimo', 'Óptimo'), ('advertencia', 'Advertencia'), ('no_acotado', 'No acotado'), ('infactible', 'Infactible'), ('error', 'Error'), ('procesando', 'Procesando')], default='procesando', help_text='Estado actual del problema', max_length=20),
        ),
        migrations.AddField(
            model_name='problemasimplex',
            name='iteraciones_realizadas',
            field=models.PositiveIntegerField(default=0, help_text='Número de iteraciones realizadas para encontrar la solución'),
        ),
        migrations.AddField(
            model_name='problemasimplex',
            name='tiempo_resolucion',
            field=models.FloatField(blank=True, help_text='Tiempo de resolución en segundos', null=True),
        ),
        migrations.AddField(
            model_name='problemasimplex',
            name='variables_artificiales',
            field=models.PositiveIntegerField(default=0, help_text='Número de variables artificiales usadas (se calcula automáticamente)'),
        ),
        migrations.AlterField(
            model_name='problemasimplex',
            name='max_iteraciones',
            field=models.IntegerField(default=100, help_text='Número máximo de iteraciones', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='problemasimplex',
            name='solucion',
            field=models.JSONField(blank=True, help_text='Solución encontrada con metadatos', null=True),
        ),
        migrations.AlterField(
            model_name='problemasimplex',
            name='tabla_final',
            field=models.JSONField(blank=True, help_text='Tabla final del simplex', null=True),
        ),
        migrations.AlterField(
            model_name='problemasimplex',
            name='tabla_inicial',
            field=models.JSONField(blank=True, help_text='Tabla inicial del simplex', null=True),
        ),
        migrations.AlterField(
            model_name='problemasimplex',
            name='tolerancia',
            field=models.FloatField(default=0.001, help_text='Tolerancia para considerar cero', validators=[django.core.validators.MinValueValidator(1e-10)]),
        ),
        migrations.AlterField(
            model_name='problemasimplex',
            name='variables_decision',
            field=models.PositiveIntegerField(default=2, help_text='Número de variables de decisión (entre 1 y 10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='problemasimplex',
            index=models.Index(fields=['usuario', 'creado'], name='metodos_pro_usuario_bb7c35_idx'),
        ),
        migrations.AddIndex(
            model_name='problemasimplex',
            index=models.Index(fields=['estado'], name='metodos_pro_estado_b2fad6_idx'),
        ),
    ]
