# Generated by Django 5.2.2 on 2025-06-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0003_problemasimplex_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemasimplex',
            name='pasos',
            field=models.JSONField(blank=True, help_text='Todos los pasos intermedios del método Simplex', null=True),
        ),
    ]
