# Generated by Django 5.2.2 on 2025-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0004_problemasimplex_pasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemasimplex',
            name='explicacion_chatgpt',
            field=models.TextField(blank=True, help_text='Explicación generada automáticamente por ChatGPT del procedimiento simplex', null=True),
        ),
    ]
