# Generated by Django 5.2.2 on 2025-07-12 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0006_diferenciacionfinita_falsaposicion_gausseliminacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diferenciacionfinita',
            name='explicacion_chatgpt',
            field=models.TextField(blank=True, help_text='Explicación generada automáticamente por ChatGPT del procedimiento simplex', null=True),
        ),
        migrations.AddField(
            model_name='falsaposicion',
            name='explicacion_chatgpt',
            field=models.TextField(blank=True, help_text='Explicación generada automáticamente por ChatGPT del procedimiento simplex', null=True),
        ),
        migrations.AddField(
            model_name='gausseliminacion',
            name='explicacion_chatgpt',
            field=models.TextField(blank=True, help_text='Explicación generada automáticamente por ChatGPT del procedimiento simplex', null=True),
        ),
        migrations.AddField(
            model_name='gaussjordan',
            name='explicacion_chatgpt',
            field=models.TextField(blank=True, help_text='Explicación generada automáticamente por ChatGPT del procedimiento simplex', null=True),
        ),
        migrations.AddField(
            model_name='interpolacionnewton',
            name='explicacion_chatgpt',
            field=models.TextField(blank=True, help_text='Explicación generada automáticamente por ChatGPT del procedimiento simplex', null=True),
        ),
        migrations.AlterField(
            model_name='gaussjordan',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
